### PR TITLE
add option to settings: Search Title only

### LINKED ISSUE #532: option 'Search for Title only' - would you accept PR?
Would you accept the following PR?

- additional switch below Sorting
- name: Searching
- default value off
- text: Search restricted to Title

Since the default is off, current users wouldn't experience a change in behaviour.

But as I've mentioned in https://github.com/MiniKeePass/MiniKeePass/issues/509#issuecomment-332705382, there are situations where searching all fields _can_ have a negative impact.

I'm asking, because I never coded Swift or for iOS before (I'm a macOS/ObjC guy). If you don't accept such a pull request, I won't waste a few hours getting this done.

Although I hope you will. :-)

### PR DESCRIPTION
**Pull request by tessus**
Allows the user to search only the title field.
In certain situations searching all fields can yield too many results.

The default is off, thus current users won't experience a change in behaviour.

closes #532

### CODE REVIEW

**Comment by tssmith7** [comment]
I had played around with the scope buttons in the search bar and they might be a really good application for this.  It would look like:

screen shot 2017-11-02 at 8 52 28 pm

**Comment by tessus** [comment]
@tssmith7 it looks nice on iPhone, but how would it look like on an iPad?

anyway, I've already added a global option to settings. so how would you suggest to make this work?

- remove the option from settings again and use only these 2 buttons?
  - should the chosen button stick or should it always start at `All Fields`?
- set the default button according to the value in settings
  - should changing the value be local or global (change the option in setttings as well)?

Personally I like the second approach with a local scope for these 2 buttons (so that the global setting won't change), but it's not my project.

if @jarush is ok with this, I can work on another PR.

**Comment by tssmith7** [comment]
I don't have an opinion as to whether the global setting is kept or not.  I just think that being able to see what the current search is showing (All Fields or Titles Only) and being able to change the setting right from the search bar is useful.  It seems much more functional than starting a search and realizing that you want to limit it to Titles only (or enlarge to All Fields) then having to cancel the search, switch to the settings view, and change the global setting.

The search function call in `DatabaseDocument` doesn't have any argument to specify the scope of the search and it may be useful to add a dictionary `options` argument that would contain some modifiers for the search.  Such as `TitlesOnly = YES`, or `ShowHidden = YES` or something.  It might be good to use a dictionary so other options can be added in the future without adding parameters to the function call.

**Comment by tessus** [comment]
I agree that it would be useful. I like the idea a lot.

However, I won't do anything unless I get the approval from the owner of this project. I won't waste my time on a PR which is then rejected and/or I'm told that it should have been done differently.

But if you want to go ahead and submit a PR, please do.

I only ask that you leave the global option in settings and use it as the default when showing the buttons. I believe that would be the most logical way for the UI.

**Pull request merged**
